id: I4A52F059
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T12:16:53+00:00'
last_modified: '2022-06-07T10:27:40.209048+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23599
  title: བཀའ་བློན་རྟོགས་བརྗོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    00A2:
      image_group_id: I1KG23677
      title: Volume 1 of bka' blon rtogs brjod/
      total_pages: 218
      order: 1
      base_file: 00A2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
